name: Build LaTeX document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Tectonic dev build
      run: |
        curl -L https://github.com/tectonic-typesetting/tectonic/releases/download/latest/tectonic-latest-x86_64-unknown-linux-musl.tar.gz -o tectonic.tar.gz
        tar -xzf tectonic.tar.gz
        sudo mv tectonic /usr/local/bin/tectonic

    - name: Compile LaTeX document with Tectonic V2
      run: |
        cd summary
        tectonic -X build

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: summary/build/main/main.pdf